swagger:
  resourcePackage: com.youtube.search.resource


########## DROPWIZARD SPECIFIC CONFIGURATION ##########
server:
  rootPath: /youtube
  applicationConnectors:
   - type: http
     port: 8088
  adminConnectors:
   - type: http
     port: 8089

  # HTTP request log settings.
  requestLog:
    appenders:
      - type: console
        threshold: INFO
        timeZone: IST
        target: stdout

# Logging settings.
logging:
  level: INFO
  appenders:
    - type: console
      threshold: INFO
      timeZone: IST
      target: stdout
    - type: console
      threshold: ERROR
      timeZone: IST
      target: stdout
    - type: file
      currentLogFilename: /tmp/searchapi.log
      archivedLogFilenamePattern: /tmp/searchapir-%d.log.gz
      archivedFileCount: 5
youtubeHttpConfig:
  httpClientTimeToLiveInMs: 10000
  httpClientMaxTotal: 10
  httpClientMaxTotalPerRoute: 10
  httpClientConnectTimeoutMs: 10000
  httpClientSocketTimeoutMs: 10000

searchRequest:
  query: cricket
  type: video
  part: ["snippet"]

schedulerConfig:
  initialDelay: 10
  period: 100000
  threadPool: 1

googleSearchApi: https://www.googleapis.com/youtube/v3/search
googleSearchApiKey: AIzaSyBCXHmn5SIGp5hFCiRniJBMLnKxAcJZrlM
elasticsearch: ["http://localhost:9200"]
indexName: video_details